### ISSUE TITLE
In-flight checklist 2

### ISSUE THREAD

**Issue by chrswng** [simplysecure/simsec-luminate#36]
**Carried over**

- [ ] Add Resources to Individual Theme pages

**Footer**

- [x] Make simsec and luminate logos same height
- [x] Link logos to websites (https://simplysecure.org/ and https://luminategroup.com/)

**Update logo icon**

- [x] Chris added svg in slack channel

**About**

- [x] Try lowering font weight for the Crimson Text
- [x] Link style regular case with thin underline (instead of CAPS)

**Individual Insight page**

- [x] Use same padding for Recommendation and Resource <img width="920" alt="Screen Shot 2019-05-28 at 3 29 35 PM" src="https://user-images.githubusercontent.com/8985721/58506705-08705800-815e-11e9-827c-b2e0a2088262.png">

**Recommendations page**

- [x] Change "Clear All" button to "Clear Filter"
- [x] Button should only show if a filter is selected

**Project Details page**

- [x] Set up figures content type (Chris but Denny guidance)
- [x] Add content (Chris)

**Foreword page**

- [x] Add content (waiting on Luminate)
