### ISSUE TITLE
Alpha checklist

### ISSUE THREAD

**Issue by chrswng** [simplysecure/simsec-luminate#49]
**Carried over from #36** 

- [x] Add Recommendations to individual Theme pages

**Global**

- [x] Use thin line hyperlink style (same style as About page) and add a hover animation

**Footer**

- [x] Add hover opacity animation to logos
- [x] Reduce Crimson Text weight
- [ ] Change "Partner Perspectives is a project of" to something (Chris to confirm)

**Insights List**

- [x] Reduce Crimson Text weight in header
- [x] Reorder Insights
- [x] Widen dropdown box

**Recommendations List**

- [x] They don't like filter, discuss

**Project Details**

- [x] Move caption to after Figure Title and left justify
- [x] Add space between figures and preceding/following content
- [x] Navigational component

**Figures**

- [x] Mockup added to Slack

**Foreword**

- [x] Line breaks for Signature
