### ISSUE TITLE
Last mile checklist

### ISSUE THREAD

**Issue by chrswng** [simplysecure/simsec-luminate#63]
**Carried over from #49** 

- [x] Change "Partner Perspectives" to something else in footer (SimSec)

**General**

- [x] Favicon (Chris)
- [x] SEO
- [x] Upload PDFs (Waiting for SimSec to provide final PDFs) - are these getting html redirects?

**Index**

- [x] Update to use themesCopy for text under Themes (sorry, it was missing, my bad)

**Insights list page**

- [x] Header copy (SimSec)

**Recommendations list page**

- [x] Header copy (SimSec)

**Project Details**

- [x] Go Back link from figures goes to top (assuming this is related to the nav element integration), fix if fixable, alternatives if not
- [x] Bump up font size for caption
- [x] Bump down font size for Text Description

**About**

- [x] Add link to details page (Chris; Contentful)
